/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grant.view;

import com.grant.data.ItemDAO;
import com.grant.entity.OutPrintDetails;
import com.grant.entity.PrintDetails;
import com.grant.entity.RepDetails;
import com.grant.report.BillPdf;
import com.grant.util.InputValidator;
import java.util.Vector;

/**
 *
 * @author Isura Amarasinghe
 */
public class FormPrint extends javax.swing.JFrame {

    /**
     * Creates new form FormPrint
     */
    static String invoNo;
    private Vector<Vector<String>> data;
    private Vector<String> header;

    public FormPrint(String invo) {
        header = new Vector<String>();
        header.add("itemName");
        header.add("itemNo");
        header.add("repCode");
        header.add("description");
        header.add("invoiceNo");
        header.add("outwards");
        header.add("type");
        header.add("balance");
        header.add("unitPrice");
        header.add("amount");
        header.add("date");

        initComponents();
        invoNo = invo;
        jLblInvoNo.removeAll();
        jLblInvoNo.setText(invoNo);
        getVariables(invoNo);
        getSubTotal(invoNo);
        loadTable(invoNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCusName = new javax.swing.JTextField();
        jTAddress = new javax.swing.JTextField();
        jCPayType = new javax.swing.JComboBox<>();
        jTNo = new javax.swing.JTextField();
        jLblRepCode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblInvoNo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLblSubTotal = new javax.swing.JLabel();
        jTDiscount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblStockOut = new javax.swing.JTable();
        jLtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTorderNo = new javax.swing.JTextField();
        jBCancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cusomer Name ");

        jLabel2.setText("Address");

        jLabel3.setText("Pay Type");

        jLabel4.setText("Cheque No");

        jLabel5.setText("Rep Code");

        jCPayType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit", "Cheque" }));
        jCPayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPayTypeActionPerformed(evt);
            }
        });

        jTNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNoActionPerformed(evt);
            }
        });

        jLblRepCode.setText("RepCode");

        jLabel6.setText("Invoice No");

        jLblInvoNo.setText("Invoice No");

        jLabel7.setText("Sub Total");

        jLblSubTotal.setText("SubTotal");

        jTDiscount.setText("0");
        jTDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDiscountKeyReleased(evt);
            }
        });

        jLabel8.setText("Discount");

        jButton1.setText("Print and Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTblStockOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "itemName ", "itemNo ", "repCode ", "description ", "invoiceNo ", "outwards ", "type ", "balance ", "unitPrice", "amount", "date "
            }
        ));
        jTblStockOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblStockOutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblStockOut);

        jLtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLtotal.setText("0.00");

        jLabel9.setText("Order No");

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblSubTotal)
                            .addComponent(jLblInvoNo)
                            .addComponent(jTCusName)
                            .addComponent(jTAddress)
                            .addComponent(jCPayType, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNo, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(jLblRepCode, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(jTorderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCPayType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTorderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLblRepCode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLblInvoNo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLblSubTotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addComponent(jLtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validateFields()) {
            PrintDetails printDetail = new PrintDetails();
            printDetail.setCustomerName(jTCusName.getText());
            printDetail.setAddress(jTAddress.getText());
            printDetail.setPayType(jCPayType.getSelectedItem().toString());
            printDetail.setOrderNo(jTorderNo.getText());
            printDetail.setNoPay(jTNo.getText());
            printDetail.setInvoiceNo(jLblInvoNo.getText());
            printDetail.setSubTotal(jLblSubTotal.getText());
            printDetail.setDiscount(jTDiscount.getText());
            printDetail.setTotal(jLtotal.getText());

            ItemDAO itemDAO = new ItemDAO();

            itemDAO.balanceHandler(printDetail);

            boolean save1 = itemDAO.addItemOutToPrint(printDetail);
            //Something wrong with invo
            boolean save2 = itemDAO.addCusDetailsToPrint(printDetail);

            BillPdf billPdf = new BillPdf();
            billPdf.printBill(printDetail);

            FormMain formMain = new FormMain();
            this.setVisible(false);
            formMain.setVisible(true);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTblStockOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblStockOutMouseClicked

    }//GEN-LAST:event_jTblStockOutMouseClicked

    private void jTDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDiscountKeyReleased

        Double subTotal = Double.parseDouble(jLblSubTotal.getText());
        String discountStr = jTDiscount.getText();

        if (discountStr.isEmpty()) {
            discountStr = "0.00";
        }

        Double discount = Double.parseDouble(discountStr);
        Double total = subTotal * ((100 - discount) / 100);
        double totalroundOff = Math.round(total * 100.0) / 100.0;

        jLtotal.setText(String.valueOf(totalroundOff));
    }//GEN-LAST:event_jTDiscountKeyReleased

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormItemOut formItemOut = new FormItemOut();
        this.setVisible(false);
        formItemOut.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCPayTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPayTypeActionPerformed
        String payType = jCPayType.getSelectedItem().toString();
        if (payType != "Cheque") {
            jTNo.setText("Not Applicable");
            jTNo.disable();
        } else {
            jTNo.setText("");
            jTNo.enable();
        }
    }//GEN-LAST:event_jCPayTypeActionPerformed

    private void jTNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrint(invoNo).setVisible(true);

            }
        });
    }

    public boolean validateFields() {
        InputValidator validate = new InputValidator();
        if (!validate.validInvo(jLblInvoNo, "Invalied Invoice NO")) {
            return false;
        } else if (!validate.validateField(jTCusName, "Please enter Customer Name")) {
            return false;
        } else if (!validate.validateField(jTAddress, "Please enter Address")) {
            return false;
        }
        return true;
    }

    public void getVariables(String invoNo) {
        ItemDAO itemDAO = new ItemDAO();
        OutPrintDetails data = itemDAO.getStockOutToPrint(invoNo);
        jLblRepCode.setText(data.getRefCode());
    }

    public void getSubTotal(String invoNo) {
        ItemDAO itemDAO = new ItemDAO();
        String subTotal = itemDAO.getPrintSubTotal(invoNo);
        jLblSubTotal.setText(subTotal);
    }

    private void loadTable(String invoNo) {
        ItemDAO dao = new ItemDAO();
        data = dao.getStockOutTbl(invoNo);
        jTblStockOut.setModel(new javax.swing.table.DefaultTableModel(data, header));
        jScrollPane1.setViewportView(jTblStockOut);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCPayType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblInvoNo;
    private javax.swing.JLabel jLblRepCode;
    private javax.swing.JLabel jLblSubTotal;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAddress;
    private javax.swing.JTextField jTCusName;
    private javax.swing.JTextField jTDiscount;
    private javax.swing.JTextField jTNo;
    private javax.swing.JTable jTblStockOut;
    private javax.swing.JTextField jTorderNo;
    // End of variables declaration//GEN-END:variables
}
